name=NocLLM
version=1.0.0
author=Muhammad Ikhwan Fathulloh <muhammadikhwanfathulloh17@gmail.com>
maintainer=Nocturnailed Community <nocturnailed.team@gmail.com>
sentence=A highly lightweight, dynamic C++ library to interact with Cloud and Local LLMs on ESP32/ESP8266.
paragraph=NocLLM natively supports streaming responses from Large Language Models (LLMs) via OpenAI-compatible endpoints. It dynamically switches between HTTPS for Cloud (OpenAI, Groq) and HTTP for Local APIs (LM Studio, Ollama). Uses a zero-dependency, ultra-lightweight custom JSON extraction approach for fast performance and low RAM usage.
category=Communication
url=https://github.com/Nocturnailed-Community/NocLLM
architectures=esp32,esp8266
includes=NocLLM.h
